#define ERROR_THRESHOLD 0.13
#define LEARNING_RATE 0.5
#define DEBUG_THRESHOLD 100
#define LAYERS 4
#define TRAIN_SIZE 961
#define MAX_LAYER_SIZE 20
#define TRAIN_FILE "../train/binadd.train"
#define NUM_INPUT_NODES 10
#define NUM_OUTPUT_NODES 6
