#define ERROR_THRESHOLD 0.13
#define LEARNING_RATE 0.5
#define DEBUG_THRESHOLD 1
#define LAYERS 4
#define TRAIN_SIZE 42000
#define MAX_LAYER_SIZE 1568
#define TRAIN_FILE "../train/digit.train"
#define NUM_INPUT_NODES 784
#define NUM_OUTPUT_NODES 10
